# Generated by Django 3.2.8 on 2022-10-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('descrition', models.TextField(null=True, verbose_name='Description')),
                ('ubication', models.TextField(max_length=100, verbose_name='Ubication')),
                ('purchase_cost', models.IntegerField(null=True, verbose_name='Purchase cost')),
                ('sale_cost', models.IntegerField(null=True, verbose_name='Sale cost')),
                ('upload_date', models.DateField(null=True, verbose_name='Upload date')),
                ('sale_date', models.DateField(null=True, verbose_name='Sale date')),
                ('imagen', models.ImageField(null=True, upload_to='imagen/', verbose_name='Imagen')),
                ('intermediary_cost', models.IntegerField(null=True, verbose_name='Intermediary cost')),
                ('profit', models.IntegerField(null=True, verbose_name='Profit')),
            ],
        ),
    ]
