# Generated by Django 3.2.8 on 2022-10-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_rename_descrition_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagens/', verbose_name='Imagen'),
        ),
    ]
