# Generated by Django 3.2.8 on 2022-10-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_alter_product_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagen/', verbose_name='Imagen'),
        ),
    ]
