# Generated by Django 3.2.8 on 2022-10-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_alter_product_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_cost',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Purchase cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_cost',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Sale cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ubication',
            field=models.CharField(max_length=100, verbose_name='Ubication'),
        ),
    ]
