# Generated by Django 3.2.8 on 2022-10-22 23:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_auto_20221022_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_cost',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Purchase Cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
