# Generated by Django 3.2.8 on 2022-10-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0006_auto_20221023_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_date',
            field=models.DateField(null=True),
        ),
    ]
