# Generated by Django 3.2.8 on 2022-10-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0007_alter_product_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.BooleanField(default=False, verbose_name='Sold'),
        ),
        migrations.AlterField(
            model_name='product',
            name='intermediary_cost',
            field=models.IntegerField(blank=True, verbose_name='Intermediary cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Profit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Sale cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_date',
            field=models.DateField(blank=True),
        ),
    ]
