# Generated by Django 3.2.8 on 2022-10-23 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0008_auto_20221024_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sold',
        ),
    ]
