# Generated by Django 3.2.8 on 2022-10-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0009_remove_product_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_cost',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Sale cost'),
        ),
    ]
