# Generated by Django 3.2.8 on 2022-10-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0010_alter_product_sale_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Sale cost'),
        ),
    ]
