# Generated by Django 3.2.8 on 2022-10-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0011_alter_product_sale_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='upload_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
