# Generated by Django 3.2.8 on 2022-10-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0012_alter_product_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.BooleanField(default=False, verbose_name='Sold'),
        ),
    ]
