# Generated by Django 3.2.8 on 2022-10-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0013_product_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sold',
            field=models.BooleanField(default=False, verbose_name='IS SOLD'),
        ),
    ]
