# Generated by Django 3.2.8 on 2022-11-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0016_alter_product_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.TextField(blank=True, null=True, verbose_name='Category'),
        ),
    ]
