# Generated by Django 3.2.8 on 2023-01-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0017_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='intermediary_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Intermediary cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ubication',
            field=models.CharField(max_length=30, verbose_name='Ubication'),
        ),
    ]
