# Generated by Django 3.2.8 on 2023-01-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0018_auto_20230112_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='intermediary_cost',
            field=models.IntegerField(blank=True, verbose_name='Intermediary cost'),
        ),
    ]
