# Generated by Django 3.2.8 on 2023-01-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0019_alter_product_intermediary_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ubication',
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(max_length=30, null=True, verbose_name='Location'),
        ),
    ]
